---Built-in editor UI groups (:h highlight-groups).
---@param r ValeRoles
---@return table<string, vim.api.keyset.highlight>
return function(r)
  return {
    Normal = { fg = r.fg, bg = r.bg },
    NormalNC = { fg = r.fg, bg = r.bg },
    NormalFloat = { fg = r.fg, bg = r.bg_float },
    FloatBorder = { fg = r.border_float, bg = r.bg_float },
    FloatTitle = { fg = r.fg_bright, bg = r.bg_float, bold = true },
    FloatFooter = { fg = r.fg_muted, bg = r.bg_float },
    FloatShadow = { bg = r.bg_chrome, blend = 80 },
    FloatShadowThrough = { bg = r.bg_chrome, blend = 100 },

    Cursor = { fg = r.bg, bg = r.cursor },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    CursorLine = { bg = r.bg_line },
    CursorColumn = { bg = r.bg_line },
    ColorColumn = { bg = r.bg_line },
    CursorLineNr = { fg = r.linenr_active },
    CursorLineSign = { link = "CursorLine" },
    CursorLineFold = { link = "CursorLine" },
    LineNr = { fg = r.linenr },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    SignColumn = { fg = r.linenr, bg = r.bg },
    FoldColumn = { fg = r.linenr, bg = r.bg },
    Folded = { fg = r.fg_muted, bg = r.bg_line },

    StatusLine = { fg = r.fg, bg = r.bg_chrome },
    StatusLineNC = { fg = r.fg_muted, bg = r.bg_chrome },
    StatusLineTerm = { link = "StatusLine" },
    StatusLineTermNC = { link = "StatusLineNC" },
    TabLine = { fg = r.fg_muted, bg = r.bg_chrome },
    TabLineFill = { bg = r.bg_chrome },
    TabLineSel = { fg = r.fg_bright, bg = r.bg },
    WinBar = { fg = r.fg, bg = r.bg },
    WinBarNC = { fg = r.fg_muted, bg = r.bg },
    WinSeparator = { fg = r.border, bg = r.bg },
    VertSplit = { link = "WinSeparator" },
    MsgArea = { fg = r.fg },
    MsgSeparator = { fg = r.border, bg = r.bg_chrome },
    ModeMsg = { fg = r.fg, bold = true },
    MoreMsg = { fg = r.accent },
    Question = { fg = r.accent },
    ErrorMsg = { fg = r.error },
    WarningMsg = { fg = r.warn },
    OkMsg = { fg = r.ok },
    Title = { fg = r.heading, bold = true },
    Directory = { fg = r.fg },
    Conceal = { fg = r.fg_muted },
    NonText = { fg = r.whitespace },
    EndOfBuffer = { fg = r.bg },
    Whitespace = { fg = r.whitespace },
    SpecialKey = { fg = r.whitespace },
    QuickFixLine = { bg = r.selection_inactive, bold = true },
    WildMenu = { fg = r.fg_bright, bg = r.selection },

    Pmenu = { fg = r.fg, bg = r.bg_float },
    PmenuSel = { fg = r.fg_bright, bg = r.selection },
    PmenuKind = { fg = r.type, bg = r.bg_float },
    PmenuKindSel = { fg = r.type, bg = r.selection },
    PmenuExtra = { fg = r.fg_muted, bg = r.bg_float },
    PmenuExtraSel = { fg = r.fg_muted, bg = r.selection },
    PmenuSbar = { bg = r.bg_float },
    PmenuThumb = { bg = r.guide },
    PmenuMatch = { fg = r.link, bold = true },
    PmenuMatchSel = { fg = r.link, bg = r.selection, bold = true },
    ComplMatchIns = { fg = r.fg_muted },

    Visual = { bg = r.selection },
    VisualNOS = { bg = r.selection_inactive },
    Search = { bg = r.search },
    IncSearch = { fg = r.fg_bright, bg = r.search_current },
    CurSearch = { fg = r.fg_bright, bg = r.search_current },
    Substitute = { fg = r.fg_bright, bg = r.search_current },
    MatchParen = { bg = r.match_paren, bold = true },
    SnippetTabstop = { bg = r.selection_inactive },

    DiffAdd = { bg = r.diff_add },
    DiffDelete = { fg = r.diff_delete_text, bg = r.diff_delete },
    DiffChange = { bg = r.diff_change },
    DiffText = { bg = r.diff_text },
    DiffTextAdd = { bg = r.diff_add_text },
    Added = { fg = r.git_add },
    Changed = { fg = r.git_change },
    Removed = { fg = r.git_delete },

    SpellBad = { sp = r.error, undercurl = true },
    SpellCap = { sp = r.warn, undercurl = true },
    SpellLocal = { sp = r.info, undercurl = true },
    SpellRare = { sp = r.hint, undercurl = true },
  }
end
