---nvim-dap signs, nvim-dap-ui, nvim-dap-virtual-text
---(plugins/dap.lua points the dap signs at Diagnostic* groups; the Dap*
---groups here are for anything that links to them.)
---@param r ValeRoles
return function(r)
  return {
    DapBreakpoint = { fg = r.error },
    DapBreakpointCondition = { fg = r.warn },
    DapLogPoint = { fg = r.info },
    DapStopped = { fg = r.ok },
    DapStoppedLine = { bg = r.search },

    DapUINormal = { fg = r.fg, bg = r.bg_chrome },
    DapUIFloatNormal = { fg = r.fg, bg = r.bg_float },
    DapUIFloatBorder = { fg = r.border_float, bg = r.bg_float },
    DapUIEndofBuffer = { fg = r.bg_chrome },
    DapUIScope = { fg = r.accent, bold = true },
    DapUIType = { fg = r.type },
    DapUIValue = { fg = r.fg },
    DapUIVariable = { fg = r.variable },
    DapUIModifiedValue = { fg = r.warn, bold = true },
    DapUIDecoration = { fg = r.accent },
    DapUIThread = { fg = r.ok },
    DapUIStoppedThread = { fg = r.accent },
    DapUIFrameName = { fg = r.fg },
    DapUICurrentFrameName = { fg = r.ok, bold = true },
    DapUISource = { fg = r.keyword_control },
    DapUILineNumber = { fg = r.linenr },
    DapUIWatchesEmpty = { fg = r.error },
    DapUIWatchesValue = { fg = r.ok },
    DapUIWatchesError = { fg = r.error },
    DapUIBreakpointsPath = { fg = r.accent },
    DapUIBreakpointsInfo = { fg = r.ok },
    DapUIBreakpointsCurrentLine = { fg = r.ok, bold = true },
    DapUIBreakpointsLine = { link = "DapUILineNumber" },
    DapUIBreakpointsDisabledLine = { fg = r.fg_muted },
    DapUIWinSelect = { fg = r.accent, bold = true },
    DapUIPlayPause = { fg = r.ok },
    DapUIRestart = { fg = r.ok },
    DapUIStop = { fg = r.error },
    DapUIStepOver = { fg = r.accent },
    DapUIStepInto = { fg = r.accent },
    DapUIStepBack = { fg = r.accent },
    DapUIStepOut = { fg = r.accent },
    DapUIUnavailable = { fg = r.fg_muted },
    DapUIPlayPauseNC = { fg = r.ok, bg = r.bg_chrome },
    DapUIRestartNC = { fg = r.ok, bg = r.bg_chrome },
    DapUIStopNC = { fg = r.error, bg = r.bg_chrome },
    DapUIStepOverNC = { fg = r.accent, bg = r.bg_chrome },
    DapUIStepIntoNC = { fg = r.accent, bg = r.bg_chrome },
    DapUIStepBackNC = { fg = r.accent, bg = r.bg_chrome },
    DapUIStepOutNC = { fg = r.accent, bg = r.bg_chrome },
    DapUIUnavailableNC = { fg = r.fg_muted, bg = r.bg_chrome },

    NvimDapVirtualText = { fg = r.inlay_fg, bg = r.inlay_bg },
    NvimDapVirtualTextChanged = { fg = r.warn, bg = r.inlay_bg },
    NvimDapVirtualTextError = { fg = r.error, bg = r.inlay_bg },
    NvimDapVirtualTextInfo = { fg = r.info, bg = r.inlay_bg },
  }
end
