---lspsaga.nvim
---@param r ValeRoles
return function(r)
  return {
    SagaNormal = { fg = r.fg, bg = r.bg_float },
    SagaBorder = { fg = r.border_float, bg = r.bg_float },
    SagaTitle = { fg = r.fg_bright, bold = true },
    SagaText = { fg = r.fg },
    SagaCount = { fg = r.fg_on_accent, bg = r.accent },
    SagaBeacon = { bg = r.accent },
    SagaSelect = { fg = r.fg_bright, bg = r.selection },
    SagaSearch = { bg = r.search },
    SagaFinderFname = { fg = r.fg_bright },
    SagaDetail = { fg = r.fg_muted },
    SagaInCurrent = { fg = r.accent },
    SagaLightBulb = { fg = r.lightbulb },
    SagaButton = { fg = r.fg_on_accent, bg = r.accent },
    SagaToggle = { fg = r.fg_muted },
    SagaSpinner = { fg = r.accent },
    SagaSpinnerTitle = { fg = r.fg_muted },
    SagaVirtLine = { fg = r.guide },
    SagaImpIcon = { fg = r.type },
    SagaFileName = { fg = r.fg },
    SagaFolderName = { fg = r.fg_muted },
    SagaWinbarSep = { fg = r.fg_muted },
    SagaWinbarFileName = { fg = r.fg },
    SagaWinbarFolderName = { fg = r.fg_muted },
    ActionPreviewNormal = { fg = r.fg, bg = r.bg_float },
    ActionPreviewBorder = { fg = r.border_float, bg = r.bg_float },
    ActionPreviewTitle = { fg = r.fg_bright, bg = r.bg_float, bold = true },
    CodeActionNormal = { fg = r.fg, bg = r.bg_float },
    CodeActionBorder = { fg = r.border_float, bg = r.bg_float },
    CodeActionText = { fg = r.fg },
    CodeActionNumber = { fg = r.number },
    FinderSelection = { fg = r.fg_bright, bg = r.selection },
    RenameNormal = { fg = r.fg, bg = r.bg_float },
    RenameBorder = { fg = r.accent, bg = r.bg_float },
    RenameMatch = { bg = r.search },
    DiagnosticBorder = { fg = r.border_float, bg = r.bg_float },
    DiagnosticNormal = { fg = r.fg, bg = r.bg_float },
    DiagnosticText = { fg = r.fg },
    HoverNormal = { fg = r.fg, bg = r.bg_float },
    HoverBorder = { fg = r.border_float, bg = r.bg_float },
    TerminalBorder = { fg = r.border_float, bg = r.bg_float },
    TerminalNormal = { fg = r.fg, bg = r.bg_float },
  }
end
