---neogit
---@param r ValeRoles
---@param c table resolved palette
return function(r, c)
  return {
    NeogitBranch = { fg = r.accent, bold = true },
    NeogitBranchHead = { fg = r.accent, bold = true, underline = true },
    NeogitRemote = { fg = r.git_add, bold = true },
    NeogitObjectId = { fg = r.constant },
    NeogitStash = { fg = r.fg_muted },
    NeogitFold = { fg = r.fg_muted },
    NeogitSubtleText = { fg = r.fg_muted },
    NeogitSectionHeader = { fg = r.keyword_control, bold = true },
    NeogitSectionHeaderCount = { fg = r.fg_muted },
    NeogitTagName = { fg = r.warn },
    NeogitTagDistance = { fg = r.fg_muted },
    NeogitFilePath = { fg = r.fg },
    NeogitCommitViewHeader = { fg = r.fg_bright, bg = r.bg_surface },
    NeogitChangeModified = { fg = r.git_change, bold = true },
    NeogitChangeAdded = { fg = r.git_add, bold = true },
    NeogitChangeNewFile = { fg = r.git_add, bold = true },
    NeogitChangeDeleted = { fg = r.git_delete, bold = true },
    NeogitChangeRenamed = { fg = r.git_change, bold = true },
    NeogitChangeUpdated = { fg = r.warn, bold = true },
    NeogitChangeCopied = { fg = r.git_change, bold = true },
    NeogitChangeUnmerged = { fg = r.warn, bold = true },

    NeogitHunkHeader = { fg = r.fg_muted, bg = r.bg_surface },
    NeogitHunkHeaderHighlight = { fg = r.fg_bright, bg = r.bg_surface, bold = true },
    NeogitHunkHeaderCursor = { fg = r.fg_bright, bg = r.bg_surface, bold = true },
    NeogitHunkMergeHeader = { fg = r.fg_muted, bg = r.bg_surface },
    NeogitHunkMergeHeaderHighlight = { fg = r.warn, bg = r.bg_surface, bold = true },
    NeogitHunkMergeHeaderCursor = { fg = r.warn, bg = r.bg_surface, bold = true },
    NeogitDiffContext = { fg = r.fg, bg = r.bg },
    NeogitDiffContextHighlight = { fg = r.fg, bg = r.bg_line },
    NeogitDiffContextCursor = { fg = r.fg, bg = r.bg_line },
    NeogitDiffAdd = { fg = r.git_add, bg = r.diff_add },
    NeogitDiffAddHighlight = { fg = r.git_add, bg = r.diff_add },
    NeogitDiffAddCursor = { fg = r.git_add, bg = r.diff_add_text },
    NeogitDiffAddInline = { bg = r.diff_add_text },
    NeogitDiffDelete = { fg = r.git_delete, bg = r.diff_delete },
    NeogitDiffDeleteHighlight = { fg = r.git_delete, bg = r.diff_delete },
    NeogitDiffDeleteCursor = { fg = r.git_delete, bg = r.diff_delete_text },
    NeogitDiffDeleteInline = { bg = r.diff_delete_text },
    NeogitDiffHeader = { fg = r.accent, bg = r.bg_surface, bold = true },
    NeogitDiffHeaderHighlight = { fg = r.accent, bg = r.bg_surface, bold = true },
    NeogitDiffAdditions = { fg = r.git_add },
    NeogitDiffDeletions = { fg = r.git_delete },

    NeogitPopupSectionTitle = { fg = r.keyword_control, bold = true },
    NeogitPopupBranchName = { fg = r.accent },
    NeogitPopupBold = { bold = true },
    NeogitPopupSwitchKey = { fg = r.keyword },
    NeogitPopupSwitchEnabled = { fg = r.string },
    NeogitPopupSwitchDisabled = { fg = r.fg_muted },
    NeogitPopupOptionKey = { fg = r.keyword },
    NeogitPopupOptionEnabled = { fg = r.string },
    NeogitPopupOptionDisabled = { fg = r.fg_muted },
    NeogitPopupConfigKey = { fg = r.keyword },
    NeogitPopupConfigEnabled = { fg = r.string },
    NeogitPopupConfigDisabled = { fg = r.fg_muted },
    NeogitPopupActionKey = { fg = r.keyword },
    NeogitPopupActionDisabled = { fg = r.fg_muted },
    NeogitFloatHeader = { fg = r.fg_bright, bg = r.bg_float, bold = true },
    NeogitFloatHeaderHighlight = { fg = r.accent, bg = r.bg_float, bold = true },

    NeogitGraphAuthor = { fg = r.string },
    NeogitGraphRed = { fg = c.error },
    NeogitGraphWhite = { fg = r.fg_bright },
    NeogitGraphYellow = { fg = c.yellow },
    NeogitGraphGreen = { fg = c.add },
    NeogitGraphCyan = { fg = c.cyan },
    NeogitGraphBlue = { fg = c.blue },
    NeogitGraphPurple = { fg = c.purple },
    NeogitGraphGray = { fg = r.fg_muted },
    NeogitGraphOrange = { fg = c.orange },
    NeogitGraphBoldRed = { fg = c.error, bold = true },
    NeogitGraphBoldWhite = { fg = r.fg_bright, bold = true },
    NeogitGraphBoldYellow = { fg = c.yellow, bold = true },
    NeogitGraphBoldGreen = { fg = c.add, bold = true },
    NeogitGraphBoldCyan = { fg = c.cyan, bold = true },
    NeogitGraphBoldBlue = { fg = c.blue, bold = true },
    NeogitGraphBoldPurple = { fg = c.purple, bold = true },
    NeogitGraphBoldGray = { fg = r.fg_muted, bold = true },
    NeogitGraphBoldOrange = { fg = c.orange, bold = true },
  }
end
