---neo-tree.nvim (VS Code explorer look: chrome background, muted guides)
---@param r ValeRoles
return function(r)
  return {
    NeoTreeNormal = { fg = r.fg, bg = r.bg_chrome },
    NeoTreeNormalNC = { fg = r.fg, bg = r.bg_chrome },
    NeoTreeEndOfBuffer = { fg = r.bg_chrome, bg = r.bg_chrome },
    NeoTreeSignColumn = { bg = r.bg_chrome },
    NeoTreeWinSeparator = { fg = r.border, bg = r.bg_chrome },
    NeoTreeVertSplit = { fg = r.border, bg = r.bg_chrome },
    NeoTreeStatusLine = { fg = r.fg_muted, bg = r.bg_chrome },
    NeoTreeStatusLineNC = { fg = r.fg_muted, bg = r.bg_chrome },
    NeoTreeCursorLine = { bg = r.bg_surface },
    NeoTreeRootName = { fg = r.fg_bright, bold = true },
    NeoTreeDirectoryName = { fg = r.fg },
    -- FolderIcon is the theme-agnostic hook plugins/neotree.lua looks for.
    FolderIcon = { fg = r.folder },
    NeoTreeDirectoryIcon = { link = "FolderIcon" },
    NeoTreeFileName = { fg = r.fg },
    NeoTreeFileNameOpened = { fg = r.fg_bright, bold = true },
    NeoTreeFileIcon = { fg = r.fg_muted },
    NeoTreeIndentMarker = { fg = r.guide },
    NeoTreeExpander = { fg = r.fg_muted },
    NeoTreeDotfile = { fg = r.fg_muted },
    NeoTreeHiddenByName = { fg = r.fg_muted },
    NeoTreeWindowsHidden = { fg = r.fg_muted },
    NeoTreeDimText = { fg = r.fg_muted },
    NeoTreeFadeText1 = { fg = r.fg_muted },
    NeoTreeFadeText2 = { fg = r.guide_active },
    NeoTreeMessage = { fg = r.fg_muted, italic = true },
    NeoTreeFilterTerm = { fg = r.link, bold = true },
    NeoTreeModified = { fg = r.warn },
    NeoTreeSymbolicLinkTarget = { fg = r.link },
    NeoTreeBufferNumber = { fg = r.fg_muted },
    NeoTreeFileStats = { fg = r.fg_muted },
    NeoTreeFileStatsHeader = { fg = r.fg, bold = true },
    NeoTreePreview = { bg = r.bg_surface },
    NeoTreeFloatNormal = { fg = r.fg, bg = r.bg_float },
    NeoTreeFloatBorder = { fg = r.border_float, bg = r.bg_float },
    NeoTreeFloatTitle = { fg = r.fg_bright, bg = r.bg_float, bold = true },
    NeoTreeTitleBar = { fg = r.fg_on_accent, bg = r.accent, bold = true },
    NeoTreeTabActive = { fg = r.fg_bright, bg = r.bg, bold = true },
    NeoTreeTabInactive = { fg = r.fg_muted, bg = r.bg_chrome },
    NeoTreeTabSeparatorActive = { fg = r.border, bg = r.bg },
    NeoTreeTabSeparatorInactive = { fg = r.border, bg = r.bg_chrome },
    -- git status (VS Code: gitDecoration.* use the gutter hues)
    NeoTreeGitAdded = { fg = r.git_add },
    NeoTreeGitUntracked = { fg = r.git_add },
    NeoTreeGitModified = { fg = r.warn },
    NeoTreeGitDeleted = { fg = r.git_delete },
    NeoTreeGitRenamed = { fg = r.git_add },
    NeoTreeGitConflict = { fg = r.error },
    NeoTreeGitIgnored = { fg = r.fg_muted },
    NeoTreeGitStaged = { fg = r.git_add },
    NeoTreeGitUnstaged = { fg = r.warn },
  }
end
