---noice.nvim
---@param r ValeRoles
return function(r)
  return {
    NoiceCmdline = { fg = r.fg, bg = r.bg_float },
    NoiceCmdlinePopup = { fg = r.fg, bg = r.bg_float },
    NoiceCmdlinePopupBorder = { fg = r.accent, bg = r.bg_float },
    NoiceCmdlinePopupTitle = { fg = r.fg_bright, bg = r.bg_float, bold = true },
    NoiceCmdlineIcon = { fg = r.accent },
    NoiceCmdlinePrompt = { fg = r.accent },
    NoiceCmdlinePopupBorderSearch = { fg = r.warn, bg = r.bg_float },
    NoiceCmdlineIconSearch = { fg = r.warn },
    NoiceConfirm = { fg = r.fg, bg = r.bg_float },
    NoiceConfirmBorder = { fg = r.accent, bg = r.bg_float },
    NoicePopup = { fg = r.fg, bg = r.bg_float },
    NoicePopupBorder = { fg = r.border_float, bg = r.bg_float },
    NoicePopupmenu = { link = "Pmenu" },
    NoicePopupmenuBorder = { fg = r.border_float, bg = r.bg_float },
    NoicePopupmenuSelected = { link = "PmenuSel" },
    NoicePopupmenuMatch = { link = "PmenuMatch" },
    NoiceMini = { fg = r.fg_muted, bg = r.bg_chrome },
    NoiceSplit = { fg = r.fg, bg = r.bg_float },
    NoiceSplitBorder = { fg = r.border_float, bg = r.bg_float },
    NoiceLspProgressTitle = { fg = r.fg_muted },
    NoiceLspProgressClient = { fg = r.accent, bold = true },
    NoiceLspProgressSpinner = { fg = r.accent },
    NoiceFormatProgressDone = { fg = r.fg_on_accent, bg = r.accent },
    NoiceFormatProgressTodo = { fg = r.fg, bg = r.bg_surface },
    NoiceFormatLevelError = { fg = r.error },
    NoiceFormatLevelWarn = { fg = r.warn },
    NoiceFormatLevelInfo = { fg = r.info },
    NoiceFormatLevelDebug = { fg = r.fg_muted },
    NoiceFormatLevelTrace = { fg = r.fg_muted },
    NoiceFormatTitle = { fg = r.fg_bright, bold = true },
    NoiceFormatDate = { fg = r.fg_muted },
    NoiceFormatEvent = { fg = r.fg_muted },
    NoiceFormatKind = { fg = r.fg_muted },
    NoiceScrollbar = { bg = r.bg_float },
    NoiceScrollbarThumb = { bg = r.guide },
    NoiceVirtualText = { fg = r.fg_muted },
  }
end
